//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework_1.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Homework_1.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на April.
        /// </summary>
        public static string april {
            get {
                return ResourceManager.GetString("april", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на August.
        /// </summary>
        public static string august {
            get {
                return ResourceManager.GetString("august", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на December.
        /// </summary>
        public static string december {
            get {
                return ResourceManager.GetString("december", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на February.
        /// </summary>
        public static string february {
            get {
                return ResourceManager.GetString("february", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Friday.
        /// </summary>
        public static string friday {
            get {
                return ResourceManager.GetString("friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на January.
        /// </summary>
        public static string january {
            get {
                return ResourceManager.GetString("january", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на July.
        /// </summary>
        public static string july {
            get {
                return ResourceManager.GetString("july", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на June.
        /// </summary>
        public static string june {
            get {
                return ResourceManager.GetString("june", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на March.
        /// </summary>
        public static string march {
            get {
                return ResourceManager.GetString("march", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на May.
        /// </summary>
        public static string may {
            get {
                return ResourceManager.GetString("may", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Monday.
        /// </summary>
        public static string monday {
            get {
                return ResourceManager.GetString("monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на November.
        /// </summary>
        public static string november {
            get {
                return ResourceManager.GetString("november", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на October.
        /// </summary>
        public static string october {
            get {
                return ResourceManager.GetString("october", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saturday.
        /// </summary>
        public static string saturday {
            get {
                return ResourceManager.GetString("saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на September.
        /// </summary>
        public static string september {
            get {
                return ResourceManager.GetString("september", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sunday.
        /// </summary>
        public static string sunday {
            get {
                return ResourceManager.GetString("sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thursday.
        /// </summary>
        public static string thursday {
            get {
                return ResourceManager.GetString("thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tuesday.
        /// </summary>
        public static string tuesday {
            get {
                return ResourceManager.GetString("tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wednesday.
        /// </summary>
        public static string wednesday {
            get {
                return ResourceManager.GetString("wednesday", resourceCulture);
            }
        }
    }
}
